### ISSUE TITLE
用-V参数看日志的时候遇到Unknown function: <SNR>20_

### ISSUE THREAD

**Issue by bstaint** [drmingdrmer/xptemplate#65]
用`vim -V9vimlog`排错的时候遇到下面的错误：
```
Error detected while processing function XPT#class:
line    6:
E700: Unknown function: <SNR>20_
E713: Cannot use empty key for Dictionary
......
```

**Comment by drmingdrmer** [comment]
Thanks for reporting this issue. :+1:  I had it fixed. Please checkout the latest master branch.

It seems verbose mode makes vim command to output extra information which confused XPTemplate from parsing function list.

**Comment by bstaint** [comment]
感谢
