### ISSUE TITLE
跟vim-polyglot插件有冲突

### ISSUE THREAD

**Issue by bstaint** [drmingdrmer/xptemplate#66]
同时使用xptemplate和vim-polyglot的时候，打开xxx.xpt.vim文件会出现：
```
Error detected while processing  D:\\...\xptemplate\ftplugin\xpt\xpt.xpt.vim:
line  31:
E688: More targets than List items
```

**Comment by bstaint** [comment]
我尝试检查了下：
发现vim-polyglot插件中也有xpt.vim文件，能不能只加载xptemplate目录和xptemplate_snippet_folders指定的目录

**Comment by drmingdrmer** [comment]
After all I added an option to filter snippet folder to load:
```
let g:xptemplate_lib_filter = ['/xpt/', 'my_snippet_.*/']
```
This let XPT to load only folder path that matches these regular expressions.

This feature is in `rc` for now: https://github.com/drmingdrmer/xptemplate/tree/rc
