### ISSUE TITLE
Invalid expression xfunc.Call

### ISSUE THREAD

**Issue by bstaint** [drmingdrmer/xptemplate#68]
新建个php文件，输入php补全会报下面的错误
```
'<input type='.xfunc.Call('Echo',[xfunc.GetVar('$_xSnipName')[1:]]).' ... />'
function XPTemplateStart..XPTparseSnippets..DoParseSnippet..<SNR>75_XPTemplateParseSnippet..XPTemplateAlias..<SNR>65_ParseTemplateSetting..xpt#eval#Eval, line 10
Vim(return):E15: Invalid expression: '<input type='.xfunc.Call('Echo',[xfunc.GetVar('$_xSnipName')[1:]]).' ... />'
...
```
检查了下，貌似是html.xpt.vim的319行的注释也被解析执行了。

**Comment by drmingdrmer** [comment]
what's you operation system and vim version? and what's the exact key
sequence you typed to produce this error?



On Wed, May 27, 2015 at 2:59 AM, bstaint <notifications@github.com> wrote:

> 新建个php文件，输入php补全会报下面的错误
>
> '<input type='.xfunc.Call('Echo',[xfunc.GetVar('$_xSnipName')[1:]]).' ... />'
> function XPTemplateStart..XPTparseSnippets..DoParseSnippet..<SNR>75_XPTemplateParseSnippet..XPTemplateAlias..<SNR>65_ParseTemplateSetting..xpt#eval#Eval, line 10
> Vim(return):E15: Invalid expression: '<input type='.xfunc.Call('Echo',[xfunc.GetVar('$_xSnipName')[1:]]).' ... />'
> ...
>
> 检查了下，貌似是html.xpt.vim的319行的注释也被解析执行了。
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/drmingdrmer/xptemplate/issues/68>.
>



-- 
要了几天饱饭就不记得西北风啥味了

**Comment by bstaint** [comment]
Windows 7 && vim 7.4.729，就补全一个php标签出现该错误。

**Comment by drmingdrmer** [comment]
I had it fixed. please checkout the latest master if your problem solved.

On Thu, May 28, 2015 at 4:14 PM, bstaint <notifications@github.com> wrote:

> Windows 7 && vim 7.4.729，就补全一个php标签出现该错误。
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/drmingdrmer/xptemplate/issues/68#issuecomment-106225324>
> .
>



-- 
要了几天饱饭就不记得西北风啥味了

**Comment by bstaint** [comment]
可以了，感谢。
