### ISSUE TITLE
关于使用<Tab>键产生的一些问题

### ISSUE THREAD

**Issue by liuzhengzhi** [drmingdrmer/xptemplate#69]
>.<由于英文渣，就用中文来描述了.
这个错误出现的很偶然，有时候<Tab>键可以正常工作，可是有时候（并不总是）写代码写到一半时候我想用Tab键来缩进，此时，就会产生错误，具体错误在下面。原谅我并不能确定是具体什么情况下按tab键会产生这个问题，我刻意尝试过许多次去重现这个问题，然而都失败了。然后今天写代码到一半又出现了。在错误产生后，如果在snippet中继续使用Tab，会导致gvim直接卡死，不能再进行其它任何操作。不知道是否有人也碰到过这个问题。
处理 function XPTforceForward..<SNR>87_FinishCurrent发生错误：
E716: Dictionary 中不存在键： mark
处理 function XPTforceForward..<SNR>87_FinishCurrent时发生错误：
E15:无效的表达式： renderContext.leadingPlaceHolder.mark
..........

**Comment by drmingdrmer** [comment]
你的键设置是什么样的？能否粘1下你的.vimrc文件看看你的配置？

**Comment by liuzhengzhi** [comment]
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"""""""""""""""""""""""""""""""""""Vunble""""""""""""""""""""""""""""""""""
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
filetype off "required!
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()
" let Vundle manage Vundle
Bundle 'gmarik/vundle'
"power-liner
Bundle 'https://github.com/LoKaltog/vim-powerline.git'
"vim-scripts repos
Bundle 'L9'
Bundle 'FuzzyFinder'
"cpp.vim
"Bundle 'cpp.vim'
"NERD tree
Bundle 'https://github.com/scrooloose/nerdtree'
Bundle 'octol/vim-cpp-enhanced-highlight'
""""""语法检查
Bundle 'scrooloose/syntastic'
""""""""""Python
""Bundle 'orenhe/pylint.vim'
"""""""YCM
Bundle 'Valloric/YouCompleteMe'
""Minibuffer
Bundle 'minibufexpl.vim'
""Taglist
Bundle 'Taglist.vim'
""xtemplete
Bundle 'drmingdrmer/xptemplate'
""jedi python的补全
Bundle 'davidhalter/jedi'
filetype plugin indent on "
""""""""""""""""""""""""""""""end of Vundle""""""""""""""""""""""""""""""""
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"""""""""""""""""""""""""""vim-powerline""""""""""""""""""""""""""""""""""
set laststatus=2
set t_Co=256
let g:Powerline_symbols='unicode'
set encoding=utf8
""""""""""""""""""""""""""""end of powerline""""""""""""""""""""""""""""""
""""""""""""""""""""""""""""""nerdter"""""""""""""""""""""""""""""""""""""
autocmd vimenter * NERDTree "设置开启vim时即打开nerdter
let g:NERDTreeWinSize=16
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif
map <C-n> :NERDTreeToggle<CR>
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTreeType") && b:NERDTreeType == "primary") | q | endif
""""""""""""""""""""""""""""""""""end""""""""""""""""""""""""""""""""""""""
"""""""""""""""""""""""""""""""ctags"""""""""""""""""""""""""""""""""""""""
set tags=tags;
"""""""""""""""""""""""""""""end"""""""""""""""""""""""""""""""""""""""""""
"""""""""""""""""""""""""""""""Taglist"""""""""""""""""""""""""""""""""""""
let Tilst_Ctags_Cmd='/usr/bin/ctags'
let Tlist_Auto_Open=1 "当打开vim时便启动
let Tlist_Show_One_File=1 "只显示当前文件的
let Tlist_Exit_OnlyWindow=1
let Tlist_Use_Right_Window=1
""""""""""""""""""""""""""""""""end""""""""""""""""""""""""""""""""""""""""
"""""""""""""""""""""""""""""""map setting"""""""""""""""""""""""""""""""""
let mapleader =","
let maplocalleader="."
""快速打开vim配置文件
nnoremap <leader>ev :vsplit $MYVIMRC<cr>
""重读vim配置文件
nnoremap <leader>sv :source $MYVIMRC<cr>
""使用外部粘贴板
nnoremap <C-v> "+gp
""防止main函数输错的映射
iabbrev mian main
iabbrev csont const
""插入我的邮箱
"iabbrev @@ liuhiter@gmail.com
""自动命令组
augroup filetype_cppc
autocmd!
""C,C++整行注释
autocmd filetype cpp nnoremap <buffer><localleader>c I//<esc>
autocmd filetype c nnoremap <buffer><localleader>c I//<esc>
autocmd filetype cpp map <F5> <Esc>:w!<CR>:!clang++ % -o %< <CR>
autocmd filetype c map <F5> <Esc>:w!<CR>:!clang % -o %< -lm <CR>
augroup END
""""""vim脚本自动折叠""""""""""""""""""""""""""""""""""""""""""""
"""""Vimscript file settings-------------{{{
augroup filetype_vim
autocmd!
autocmd FileType vim setlocal foldmethod=marker
augroup END
"}}}
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
""""<F5>"""""""""""""""""""""""""""""""""""""""""""""""""""""""""
""""""""""""""""""""""""""""""end"""""""""""""""""""""""""""""""""""""""""
"""""""""""other things""""""""""""""""""""""""""""""""""""""""""""""""""""
set number ""显示行号
set encoding=utf8
set nocompatible "关闭vi兼容
set tabstop=4	"设定tab = 4
set softtabstop=4
set shiftwidth=4
""实现语法高亮
syntax enable
syntax on
""搜索高亮
set hlsearch incsearch
""背景
colorscheme PerfectDark
""隐藏状态栏，美观一下
set guioptions=Pr
""覆盖文件时不备份
set nobackup
""编辑时不产生交换文件
set noswapfile
""开启自动缩进
set autoindent
""开启新行时自动缩进
set smartindent
""C样式缩进
set cindent
""使用Tab缩进
set smarttab
""""""""""""""""""""end""""""""""""""""""""""""""""""""""""""""""""""""""""
""""""""""""""""""""YCM""""""""""""""""""""""""""""""""""""""""""""""""""""
set completeopt=longest,menu,preview
autocmd InsertLeave * if pumvisible()==0|pclose|endif
inoremap <expr><CR> pumvisible()?'<C-y>':'<CR>'
let g:ycm_collect_identifiers_from_tags_files=1
let g:ycm_min_num_of_chars_for_completion=2
let g:ycm_cache_omnifunc=0
let g:ycm_seed_identifiers_with_syntax=1
let g:ycm_confirm_extra_conf=0
""""""""""""""""""""""""end""""""""""""""""""""""""""""""""
""""""""""""""""""""""""syntastic""""""""""""""""""""""""""
""let g:syntastic_ignore_files=[".*\.py$"]
""""""""""""""""""""""""xptemplate"""""""""""""""""""""""""
let g:xptemplate_vars="SPcmd=&BRloop=\n"
let g:xptemplate_vars.="&BRfun= "
let g:xptemplate_vars.="&SParg="
let g:xptemplate_brace_complete ='([{"<'
let g:xptemplate_vars.="&author=liu"
let g:xptemplate_vars.="&email=liuhiter@gmail.com"

**Comment by drmingdrmer** [comment]
修正了1下，更新到最新的master 应该可以修正这个问题，是因为在使用模板过程中切换到其他buffer会引起map的记录信息错误。折腾了1会找到了重现方式：展开1个模板，切换到另1个文件，再回来，再在模板之外打几个字符（这时下面会有提示XPTemplate session ends: XPT:changes outside of place holder)，这时再按<tab>可以复现问题。

如果这个过程在更新前后2个版本上可以重现和不重现错误，可以确认问题被修正了。

非常感谢提供的反馈信息，对我帮助非常大 :+1:
