### ISSUE TITLE
请问JAVA该用哪一种呢？

### ISSUE THREAD

**Issue by wsdjeg** [drmingdrmer/xptemplate#71]
我在/honza/vim-snippets上看到你的插件。
他说的一共有四个，请问这四个有什么区别，我主要写的是JAVAjsp html 用哪一个比较合适
github.com/SirVer/ultisnips:
python, supports all snippets in this repo.
github.com/garbas/vim-snipmate:
VimL, snipmate-snippets, engine sometimes behaves strange. Supports snippets/*
github.com/Shougo/neosnippet:
VimL, supports snippets/* with some configuration.
github.com/drmingdrmer/xptemplate

**Comment by drmingdrmer** [comment]
功能都差不多。xptemplate的snippet定义的语法和其他几个有差异。其他3个之间也有些差异。

简单地snippet用ultisnips或snipmate。差别不大。xptemplate功能很多。有些不是很常用。

如果是html貌似zencode也不错。

On Thu, Aug 13, 2015 at 12:52 PM, Wang Shidong <notifications@github.com>
wrote:

> 我在/honza/vim-snippets上看到你的插件。
> 他说的一共有四个，请问这四个有什么区别，我主要写的是JAVAjsp html 用哪一个比较合适
> github.com/SirVer/ultisnips:
> python, supports all snippets in this repo.
> github.com/garbas/vim-snipmate:
> VimL, snipmate-snippets, engine sometimes behaves strange. Supports
> snippets/*
> github.com/Shougo/neosnippet:
> VimL, supports snippets/* with some configuration.
> github.com/drmingdrmer/xptemplate
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/drmingdrmer/xptemplate/issues/71>.
>



-- 
要了几天饱饭就不记得西北风啥味了

**Comment by wsdjeg** [comment]
感谢你的回答,我目前刚入门java 听到别人对VIM贬低 说java非要用IDE 绝对不该是这样的,于是一致坚持用VIM 一些常见的功能基本都可以实现了,想试试你的这个插件的,不知道对于java的支持怎么样

**Comment by drmingdrmer** [comment]
日常使用功能上肯定没问题，其实大多数人都是按照个人喜好选的：D

发自我的 iPhone
