### ISSUE TITLE
为什么没有中文说明

### ISSUE THREAD

**Issue by fedkey** [drmingdrmer/xptemplate#75]
首先很赞赏作者的能力，再者，为什么没有中文说明？我敢说，很多人的技术障碍是语言上的障碍，难道你的东西都是面向老外？如果可以的话，建议双语写说明。再次感谢

**Comment by drmingdrmer** [comment]
谢谢, 我找时间写写哈.

2015-12-30 9:28 GMT+08:00 暮色连城 <notifications@github.com>:

>
> 首先很赞赏作者的能力，再者，为什么没有中文说明？我敢说，很多人的技术障碍是语言上的障碍，难道你的东西都是面向老外？如果可以的话，建议双语写说明。再次感谢
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/drmingdrmer/xptemplate/issues/75>.
>



-- 
要了几天饱饭就不记得西北风啥味了
