### ISSUE TITLE
javascript  es6 有问题

### ISSUE THREAD

**Issue by holybreath** [drmingdrmer/xptemplate#77]
因为能识别html 里的js 所以一直用的很好，但貌似对 es6 里 class 内部的方法识别报错
snippet 还是能正常插入，但会报错，得多按几次enter

例如 在如下 代码 写for 以后 调用snippet 完成
class MainStore {
  constructor() {
    for
  };
}

截图传不上来，出错信息：
处理 function XPTemplateStart .......时发生错误
第 18 行： 
E713 Dictionary 的键不能为空 
谢谢

**Comment by drmingdrmer** [comment]
怎么在html 里确定是es6? 你是说 es6之前的不会出错吗?

**Comment by holybreath** [comment]
es 5 里function这种语法，是没问题的：

> function getRandomElement(arr) {
  return arr[Math.floor(Math.random()*arr.length)];
}

es6 里有了class，这种情况下就会报之前的错误：

> class MainStore {
  constructor() {
      };
  setPlaceVisible(place){
      }
  goToPlace(place) {    
  }
}

需要的话请给我你的email，我把js 和截屏发过去。现在一直没办法在github上上传文件。。。

**Comment by drmingdrmer** [comment]
恩..是说文件本身不需要任何更改,只是 js 的上下文有变化就会产生错误?

drdr.xp@gmail.com 邮箱联系吧

**Comment by holybreath** [comment]
邮件已发，请查收

**Comment by drmingdrmer** [comment]
#44 这个是不是一样的问题? 更新最新版本可以修正这个问题.

**Comment by holybreath** [comment]
更新最新版后问题已解决，多谢！

**Comment by drmingdrmer** [comment]
👍 👍
