### ISSUE TITLE
statusline

### ISSUE THREAD

**Issue by blub123muh** [drmingdrmer/xptemplate#78]
Dear drmingdrmer,

After a couple years of vim, I finally decided to give a snippets plugin a try, and your one's was my first choice.
Right after experiencing great joy of inserting some example python snippets, I noticed that my statusline was corrupted. I am using [flagship](https://github.com/tpope/vim-flagship) by Tim Pope.
After some investigations i found out that XPTemplate checks for existence of XPMautoUpdate in statusline, and occasionally replaces your statusline with the default one. (see plugin/xpmark)
While I appreciate your effort to provide a statusline flag at all, I am slightly disturbed by the behaviour of brute-force replacing my statusline. [I also tried to manually add the XPMautoUpdate function to my statusline but it did not help]
It surely, may be caused by some conflicts with flagship, but I suppose that your heuristics of replacing are a little too aggressive? Some further investigations show that the error occurs only in the first buffer, where the statusline is set to:
`statusline=%<%f %h%m%r%=%-14.(%l,%c%V%) %P%{XPMautoUpdate("statusline")}`
In all following buffers, the statusline seems to be set correctly:
`statusline=%!flagship#statusline().XPMautoUpdate("statusline")`
Is the XPMautoUpdate call in the status line really necessary or can you make it optional for the user to decide?

**Comment by drmingdrmer** [comment]
It is necessary to have a way for XPT to check buffer changes and update marks.
And for now the only way I can find that is reliable is in event triggered when VIM updates statusline or ruler. (CursorMove event does not trigger all the time).
That's why I added an function to statusline or ruler to track cursor movement when user types something.

XPT tried to not to break statusline setting when adding something into it. I am having a look at flagship to why XPT breaks things.

You said your statusline corrupted, what do you mean about it? statusline does not display correct text or it raises some error?

**Comment by blub123muh** [comment]
The statusline is corrupted in terms of being reverted to its default.
As I stated in the last paragraph: The problem only occurs in the first buffer opened, but it works fine for the next ones. Note that flagship takes some basic statusline definition in order to create its own.


My humble idea: Maybe the order of loading Plugins matter, since it is only problematic in the first buffer.
I guess that for subsequent buffers, flagship takes the modified statusline (with XPTemplate in there) and creates a new one. Only in the first buffer, the "flagshipped" statusline gets overwritten because XPT is loaded after Flagship.

I can try to switch out the loading order (XPT before flagship) and report if the problem stilll occurs.
But for, I disabled XPT completely because of it's much more devastating conflict with CtrlP (see other issue)

Best Regards,
lpag

**Comment by drmingdrmer** [comment]
XPT always check if statusline has been set up before adding default format to statusline. And if there is something set, XPT only appends an additional piece of code at the end.

I've removed default setting up when `BufEnter`, similar to the issue with ctrlp.

Now XPT initializes statusline only when the first time user uses it.
