### ISSUE TITLE
Can't map <CR> (enter) for xptemplate_nav_next

### ISSUE THREAD

**Issue by maskedbyte** [drmingdrmer/xptemplate#84]
I would really like to remap enter to xptemplate_nav_next, it seems like the perfect key for this to me because I already use Tab for my autocompletion. Sadly, it only partially works; with Enter, I can jump to the next piece of the snippet as expected without editing it, but if I edit a piece of the snippet (by start typing) and then press enter to go to the next one, it just inserts a new line.

Maybe some remapping trick or vimrc "function!" is possible for this?

**Comment by drmingdrmer** [comment]
In my design entering a `<CR>` is a feature that lets user enter multiline text in a snippet placeholder.

Can you show me all of your xptemplate related configuration thus I can figure out how to fulfil your need.

**Comment by maskedbyte** [comment]
Hm, I haven't seen a snippet I use so far that it would make much sense to use a newline in a placeholder. Here are my xptemplate configuration vars, I did not change much:
```
let g:xptemplate_brace_complete = ""
let g:xptemplate_vars = "SParg=&BRfun=\n"
let g:xptemplate_nav_cancel = "<S-Tab>"
let g:xptemplate_nav_next = "<CR>"
```

**Comment by drmingdrmer** [comment]
I pushed a commit to master to fix this issue, please upgrade and see if it fixed your issue: xptemplate did not considered using a `<CR>` as next-ph key mapping. Thus an internal keymapping to fix multi-line place holder overrides user-mapping.

Now if a user uses `<CR>` as go-to-next key, xptemplate adds this key mapping after internal mapping.

**Comment by maskedbyte** [comment]
Thank you, it worked!
