### ISSUE TITLE
Regular Expression Support

### ISSUE THREAD

**Issue by kompleksanda** [drmingdrmer/xptemplate#88]
I'm a expert user of your templates, and I've written tons of templates and even improve the engine in my private installation. I've tried hard to include Regular Expression support, but due to my simple understanding of the Vim Language I couldn't do more or less.

Xptemplate is better than Ultisnip in many ways and a lot of users don't understand this. What they see first is the regular Expression support and context awareness of Ultisnip. It will be very good if your could add these abilities to Xptemplate.

As I said earlier Ive written quite some Xptemplate snippets. You can check it out at my repository called MyXPT.

If you need any help in writting snippets pls, I'm always available to talk too. Thanks.

**Comment by drmingdrmer** [comment]
Thanks. But what exactly do you mean **regular expression support**?
Can you give a sample use-case about how you want to use reg-exp?

**Comment by kompleksanda** [comment]
1. AUTO TRIGGER

This is an excerpt from Ultisnip documentation:

Consider following snippets, that can be usefull in Go programming:
------------------- SNIP -------------------
snippet "^p" "package" rbA
package ${1:main}
endsnippet

snippet "^m" "func main" rbA
func main() {
	$1
}
endsnippet

When "p" character will occur in the beginning of the line, it will be automatically expanded into "package main". Same with "m" character. There is no need to press trigger key after "m""

Auto Trigger can improve User Experience by saving users the need to type the trigger key. It will appear to the User as though the snippet knew automatically what needs to be typed next.

The text in the current line, or lines above or below the current line may be used to determined context of snippet trigger.

This may be done by including extra information in the snippet header about the regular Expression it uses. And also include a hint that specifies if this snippet  uses autotrigger.
E.g

XPT package reg='\V\^p\$' autotrig
package `main^

The reg='\V\^p\$' specifies that this snippet uses regular expression and has a value '\V\^p\$'
The "autotrig" specifies that this snippet can be automatically triggered.

I know XPT has "abbr" to specify abbreviation but that only works if a user types space. But autotrigger works as long as the context of what is being typed matches any snippet that has autotrigger.

2. Snippets with Regular Expression Support
This featured is almost like the auto trigger. But the difference is the snippet doesnt autotrigger. But triggers only if the user has typed the trigger key and the context around what is typed  matches the regular expression for the snippet.

Example: Just like the lorem snippet from Emmet plugin can take any arbitrary number to specify the number of dummy words to insert. i.e 

"lorem10" will Insert 10 dummy words
"lorem20" will insert 20 dummy words
'lorem\d+" will insert the number of specified words

So instead of defining a template for every possible number that can be added to "lorem" we can use just a template that support regular expression.

In XPTemplate it can be like this
The header may be like this:

XPT lorem reg='\V\blorem\(\d\+\)'

So there should be a way of capturing regular expression groups( the \d\+ part if the regular expression), so that the decimal part of what is type can be obtained and then used in the logic of the snippet to generate the dummy text.

Thats all about it. Regular Expression snippets are vital features of a snippet engine and it will be a huge plus if XPTemplate has the feature.

Thanks for the reply. If you need any help, I'm ready to help.

**Comment by drmingdrmer** [comment]
- About the auto-trigger:
  
  It is considered before but there are several problems:
  
  Context based trigger is complex, not only the position of cursor, but also syntax name at cursor, surrounding text and surrounding lines are all candidate conditions to check. A simple reg-exp is not enough.
  To my opinion, the best way is a user defined function to do that.
  Following config auto trigger a snippet named "sh" in "*.sh" files.

```
fun! AutoSnip() "{{{
    if getline(".") == 'sh'
        call feedkeys("\<Tab>")
    endif
endfunction "}}}
au CursorMovedI *.sh call AutoSnip()
```

It is not hard to define a list of keyword to auto trigger a snippet I believe.

- I had a development branch with the zencode like dynamic snippet support. But while I've been working on this feature I found it brings in too many problems than it solves.

First a lot non-keywords must be considered as keyword to find a snippet name match.
E.g. If you have a snippet `my_snippet` and `-` is considered as a valid char in reg-exp snippet name, then `-my_snippet` will not trigger.
And allowing reg-exp snippet name leads to multiple match in a line, which is very annoying.

Second XPT tries to speed up snippet name matching with A LOOOOOT snippet defined.
If reg-exp snippet is allowed, there won't be a explicit way to speed up matching.
Currently I use a prefix tree to search. Thus reg-exp snippet support would makes XPT very slow.

**Comment by kompleksanda** [comment]
Thank you.

I have another issue. I should probably open this as a new issue, but I could do that here.

When two placeholders from the same item are on the same line in a snippet text, where the first placeholder is a non-key placeholder and the second is a key placeholder. The focus comes to the key placeholder as normal but as you type a couple of text on the key placeholder the non-key placeholders before it doesn't reflect the original text type it chops a couple of characters from it. And even some text before the key-placeholder is chopped off.

Example

XPT example
`this^ changes as ``this^ is changed

The second "this"  contains the true text typed and you would expect the first  "this" to contain same text, but fails to do so

So, after expanding the snippet and typing "alexander"
The output is:

exander changes aalexander is changed

You can see the "as" has combined with "alexander" to give "aalexander" by chopping off "s ".
Also the first placeholder is now "exander" instead of "alexander".

Things gets worser if there are more non-key placeholders before the key-placeholder on the same line. So given a snippet::

XPT example
`this^ changes `this^ as ``this^ is changed

After expanding and typing "alexander", it becomes:

der changes ders ander is changed

In this case, I have no idea what happened.

My Observations: This snippet works fine as long as you typed less than 3 characters on the key-placeholder. Or if the key-placeholder was defined separately in a new line. Or if it comes before any non-key placeholder on the same line.

I tried poking into the code to see what might cause it but to no avail. I propose the problem might have arose in the Marks mangement as text is changed. Maybe the marks were not updated correctly or updated at all at some point during typing.

I will be glad if is this looked into, Thanks for your reply on Regular Expression support. I just have to seal my fate that XPT can't have the feature.

**Comment by drmingdrmer** [comment]
Hm... about the placeholder messing up issue, I can't reproduce it.

But I do experienced problems like this: Most of them are caused by plugins that interfering user input.
XPT updates marks every time user press a key. But if another plugin changes what user typed, XPT might not track text changes correctly.
Some auto-complete plugins have such issues with XPT.

This is a weakness of XPT. The reason I choose this way because it is the least interfering: do not change user actions, just track it.
Another snippet engine(I forgot the name, may be ultrasnip) remaps all of the letter from a to z as I remembered.
That is a more stable implementation.

**Comment by kompleksanda** [comment]
You are right the problem was caused by the AutoCmpl plugin, an auto completion plugin I installed. I disabled it, and voila! Everything works perfectly.

So far you have addressed all the issues I have with Xptemplate, thanks for sticking out to reply me. I use XPT 
and write snippets everyday so your replies has been most informative, thank you once again.

Now I can close this issue.
