### ISSUE TITLE
Issues with ontimeFilters of mirrors

### ISSUE THREAD

**Issue by kompleksanda** [drmingdrmer/xptemplate#89]
Hello, I'm here again.

I have issues with ontimeFilters on mirrors of placeholders. I don't understand the behavior, it works and also doesn't work.

Here is an XSET snippet I'm constructing of XPT files

```

XPT xset
\XSET`m^ `key^`.`event^`m^execute('if'.string(V()).'==""|return"="|else|return"\n"|endif')^`value^`m^execute('if'.string(V()).'==""|echo""|else|echo"\nXSETm END"|endif')^


```

This looks unclean but it's simple, contains m, key, event and value as items. The item m has two mirrors and each has it's own ontimeFilter, which execute some vim code.

What I want to achieve is when I keep or remove the "m" leadingPlaceHolder, it updates the first mirror to either "=" or "\n", then it updates the second mirror to either "" or "\nXSETm END" respectively.

If I expand the snippet and keep "m", it should become

XSETm key.event
value
XSETm END

Else if i remove m by deleting it or hitting enter key, it should result to

XSET key.event=value

Now, the problem is the second mirror works as expected, but the first doesnt, it doesnt update as I keep or clear "m".

I know there are alot of ways to acheive the effect I'm trying to create, I have actually re-written it with postFilters and it worked fine. But I love this way more because it updates as you type.

Can you fix this behaviour? I have ran through the code multiple times but I couldn't find a fix. Also, please if you fix it l'd want you to let me know what caused it and what you changed in the code to fix it, because I have modify my local installation of XPTemplate to my taste, I'd want to replicate the exact change.

Thanks for your time.

**Comment by drmingdrmer** [comment]
Got it. Let me have a look at your issue. Your snippet is complicated I do not understand it yet. :)

**Comment by drmingdrmer** [comment]
Before figuring out what's going wrong, my first thought is that `execute` is not one of the best way to do that. It makes the snippet hard to read.

I think a possible cause is about `execute`. And a first shot is a clear implementation of your need as follow:

```
fun! s:f.MapTo(expected, matchedvalue, unmatchedvalue)
    if self.V() == a:expected
        return a:matchedvalue
    else
        return a:unmatchedvalue
    endif
endfunction

XPT xss
\XSET`m^ `key^`.`event^`m^MapTo("", "=", "\n")^`value^`m^MapTo("", "", "\nXSETm END")^

```

**Comment by drmingdrmer** [comment]
I think the issue of your snippet is that when evaluating `execute('if'.string(V())...`, the code is translated to `execute('if' . string(self.V()) ...`. 
But `execute` run the code as a standalone vim script thus the `self` variable is not in the context, and finally execute results in an error.

**Comment by kompleksanda** [comment]
Yeah, it worked, you saved my ass again! Thanks.
