### ISSUE TITLE
html_cont_helper is bit buggy, I guess.

### ISSUE THREAD

**Issue by roket1428** [drmingdrmer/xptemplate#90]
When you use it one after the other as in (`tab` is the trigger key):

input: `div<tab><cr>div<tab><cr>div<tab><cr>`
output: 
```html
<div>
	 <div>
			<div>
				 
		</div>
 </div>
</div>
```
It has to be like that:
```html
<div>
	<div>
		<div>

		</div>
	</div>
</div>
```

**Comment by drmingdrmer** [comment]
Thanks for letting me know this!

It seems to be a fault of the latest vim html indent.
The function(`HtmlIndent()` in `vim/runtime/indent/html.vim`) calculating html indent moves the cursor 1 lines up.
Thus xptemplate would get a wrong line number after evaluating html indent size.

The patch has been applied to the latest master. Check it up and thanks!

**Comment by roket1428** [comment]
> Thanks for letting me know this!
> 
> It seems to be a fault of the latest vim html indent.
> The function(`HtmlIndent()` in `vim/runtime/indent/html.vim`) calculating html indent moves the cursor 1 lines up.
> Thus xptemplate would get a wrong line number after evaluating html indent size.
> 
> The patch has been applied to the latest master. Check it up and thanks!

Thanks a lot sir!
