### ISSUE TITLE
Bugs with langmap.

### ISSUE THREAD

**Issue by roket1428** [drmingdrmer/xptemplate#91]
It basically does not work with `langmap`. I think there are things like `normal` without `!`.

**Comment by roket1428** [comment]
> What do you mean about the **does not work**?
> According to `:help langmap` it affects only in `normal` mode.
> What did you do? What did you expect and what did you actually get?

Oh, sorry I forgot to add actual behavior to the comments section. :)

Normal behavior as you know is when you use `<tab`> as expanding key and `<tab>` as fallback key, it will expand the snippet if there's a keyword to trigger (like `for` for for loops) and if there's not, it will just return `<tab>` (like it will indent based on indentation settings of vim). But it doesn't return `<tab>` and just returns `<Plug>XPTfallback`. (tested with both explicitly setting `g:xptemplate_fallback` and letting it empty, only setting `g:xptemplate_key`)

**Comment by drmingdrmer** [comment]
May I have a look at your `.vimrc`?
And what is your vim version?
And I do not know whether this issue relates to the `langmap` setting you mentioned.
What is the value of your `langmap`?

**Comment by roket1428** [comment]
1. ```vim
call plug#begin('~/.config/nvim/bundle')
Plug 'drmingdrmer/xptemplate'
call plug#end()

let g:xptemplate_key = "<tab>"
let g:xptemplate_key_visual = "<tab>"
let g:xptemplate_nav_prev = "<a-tab>"
let g:xptemplate_fallback = "<tab>"
let g:xptemplate_snippet_folders = [$XDG_CONFIG_HOME . "/nvim/snips"]

set langmap=kh,mj,lk,yl,KH,MJ,LK,YL,İI,üy,ÜY,td,TD,öx,ÖX
cno <a-h> <left>
cno <a-j> <down>
cno <a-k> <up>
cno <a-l> <right>

no <a-v> <c-v>
no <a-r> <c-r>

ino <a-e> <c-n>
ino <a-i> <c-p>

no j g<down>
no k g<up>
no $ g$
no 0 g0
no ^ g^

nn <leader>vh <C-w><left>
nn <leader>vj <C-w><down>
nn <leader>vk <C-w><up>
nn <leader>vl <C-w><right>

nn <leader>vH <C-w>>
nn <leader>vJ <C-w>-
nn <leader>vK <C-w>+
nn <leader>vL <C-w><

cno w!! w !sudo tee % >/dev/null

nno <tab> za
xno <tab> zf
nno <expr> <a-tab> &foldlevel ? "zM" : "zR"

nno <silent> <a-w> :w<cr>
ino <silent> <a-w> <esc>:w<cr>a

tno <a-tab> <c-\><c-n>

for i in range(10)
  if !i
    nno <a-0> 10gt
    no! <a-0> <esc>10gt
    continue
  endif
    exe "nno <a-" . i . "> <esc>" . i . "gt"
    exe "no! <a-" . i . "> <esc>" . i . "gt"
endfor
```
2. NVIM v0.4.2
3. Vimrc includes that.

**Comment by roket1428** [comment]
Thanks. Will you add rust snippets?

**Comment by drmingdrmer** [comment]
> Thanks. Will you add rust snippets?

I am not very familiar with rust. If you have a collection of rust snippet I'd like to merge it.

**Comment by roket1428** [comment]
> > Thanks. Will you add rust snippets?
> 
> I am not very familiar with rust. If you have a collection of rust snippet I'd like to merge it.

I actually have but I'm trying to make it better like rust have some syntax that have curly bracelets in it. Like if { ... }, match { ... }, else { ... }... So, I need to think a good name to alias it for example. :) I also need to learn vim scripting (at least better than now) to be able to make efficient things. :9

**Comment by drmingdrmer** [comment]
In my opinion, complicated snippets are not popular.
The very essential snippets are the simplest `for`, `if` etc.
If you already have these simplest snippets defined well, it is never too early to publish them. :)

**Comment by roket1428** [comment]
> In my opinion, complicated snippets are not popular.
> The very essential snippets are the simplest `for`, `if` etc.
> If you already have these simplest snippets defined well, it is never too early to publish them. :)

If you want to, I'm glad to share them. :) But I need to understand some of the functions etc for be able to do a proper thing. Like spacing between `if` and the curly bracket etc, there's a global variable inside snippet files.

It is currently looks like this:
```
XPTemplate priority=lang

XPT curly hidden " $_xSnipName { .. }
`$_xSnipName^ {
	`cursor^
}

XPT icurly hidden " $_xSnipName { .. }
`$_xSnipName^ `^ {
	`cursor^
}

XPT fn synonym=function hint=fn\ ..\ in\ ..\ ..\ endfor
XSET arg*|post=ExpandIfNotEmpty(', ', 'arg*')
fn `name^(`arg*^)` -> `type?^ {
	`cursor^
}

XPT main wrap " fn main\()
fn main() {
    `cursor^
}

XPT println " println!\("...")
XSET arg*|post=ExpandIfNotEmpty(', ', 'arg*')
println!("`^"`, `arg*^);

XPT for wrap " for .. in .. { ... }
for `value^ in `list^ {
	`cursor^
}

XPT loop alias=curly " loop { ... }

XPT if wrap alias=icurly " if .. { ... }
XPT match wrap alias=icurly " match .. { ... }
XPT struct wrap alias=icurly " struct .. { ... }
XPT enum wrap alias=icurly " enum .. { ... }
XPT mod wrap alias=icurly " mod .. { ... }
XPT impl wrap alias=icurly " impl .. { ... }
```
