### ISSUE TITLE
关于 markdown link tab 切换的问题

### ISSUE THREAD

**Issue by Jiiiiiin** [drmingdrmer/xptemplate#94]
请问 在md 文件格式 link snippet 中最后一个 tab 之后出入完还会剩下一个 `~` 号，怀疑是插件的placeholder ，但是没找到解决方案，请问下，要怎么快速完成这个用例呢？

**Comment by drmingdrmer** [comment]
你在哪定义的snippet, snippet什么样子? 输入什么, 之后得到什么?

然后还有你的vim版本和系统版本都是什么?

**Comment by Jiiiiiin** [comment]
![](http://qiniu.jiiiiiin.cn/6QkQah.png)
重装了一下插件效果是这样的；

url 后面跟着一个title?

---

snippet 使用的是默认插件自带的：

```bash
❯ cd /Users/jiiiiiin/.vim/plugged/xptemplate/ftplugin/markdown
❯ ll
total 8
-rw-r--r--  1 jiiiiiin  staff   1.8K Feb 17 23:24 markdown.xpt.vim
```

系统：
![](http://qiniu.jiiiiiin.cn/iOFdxs.png)

**Comment by drmingdrmer** [comment]
第一个图片找不到. github comment可以直接粘贴图片的

**Comment by drmingdrmer** [comment]
url 后面是有个title, 带`?` 的placeholder是可选的, 直接按tab可以跳过.

**Comment by Jiiiiiin** [comment]
![](http://qiniu.jiiiiiin.cn/6QkQah.png)

**Comment by Jiiiiiin** [comment]
@drmingdrmer 好的麻烦你了 谢谢
